---
abstract: "use Google's Picasa Web API"
author:
  - 'Andrew Sterling Hanenkamp <hanenkamp@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Google-PicasaWeb
requires:
  IO::Prompt: 0
  LWP::UserAgent: 0
  Moose: 0
  MooseX::Role::Matcher: 0
  Net::Google::AuthSub: 0
  Test::Able: 0.09
  Test::Able::Runner: 1.000
  Test::Mock::LWP: 0
  URI: 0
  XML::Twig: 3.30
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Net-Google-PicasaWeb
  repository: git://github.com/zostay/net-google-picasaweb.git
version: 0.11
