---
abstract: 'use Google''s Picasa Web API'
author:
  - 'Andrew Sterling Hanenkamp <hanenkamp@cpan.org>'
build_requires:
  Test::Mock::LWP: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.750'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Net-Google-PicasaWeb
no_index:
  directory:
    - inc
    - t
requires:
  LWP::UserAgent: 0
  Net::Google::AuthSub: 0
  URI: 0
  XML::Twig: 0
version: 0.01
