---
abstract: "use Google's Picasa Web API"
author:
  - 'Andrew Sterling Hanenkamp <hanenkamp@cpan.org>'
generated_by: 'Dist::Zilla version 1.100130'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Google-PicasaWeb
requires:
  ExtUtils::MakeMaker: 6.11
  IO::Prompt: 0
  LWP::UserAgent: 0
  Moose: 0
  MooseX::Role::Matcher: 0
  Net::Google::AuthSub: 0
  Test::Able: 0.09
  Test::Able::Runner: 1.000
  Test::Mock::LWP: 0
  URI: 0
  XML::Twig: 3.30
resources:
  repository: http://github.com/zostay/net-google-picasaweb
version: 0.09
